// <auto-generated />
namespace SpodIgly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class orderuserrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderuserrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201708041203442_order-user-relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
